stages:
  - test
test:
  stage: test
  script:
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip python3
  - pip3 install -r requirements.txt
  - python3 manage.py makemigrations
  - python3 manage.py migrate
  - python3 manage.py test
