# Generated by Django 3.0.2 on 2020-01-19 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0002_group_expense_group_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group_expense',
            name='this_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.group'),
        ),
        migrations.AlterField(
            model_name='group_expense',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group_income',
            name='this_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.group'),
        ),
        migrations.AlterField(
            model_name='group_income',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group_member',
            name='this_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.group'),
        ),
        migrations.AlterField(
            model_name='group_member',
            name='this_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='income',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
