# Generated by Django 3.0.2 on 2020-01-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_expense_group_expense_group_income_group_member_groupha_income'),
    ]

