# Generated by Django 3.0.2 on 2020-01-20 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200120_1208'),
    ]

  
