# Generated by Django 3.0.2 on 2020-01-20 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0008_expense_group_expense_group_income_group_member_groupha_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='temporary_group_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('this_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.groupha')),
                ('this_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
